spring:
  datasource:
    url: jdbc:mysql://localhost:13306/meddb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_info_id
            revision_type_field_name: revision_type
    show-sql: true
  # traducao dos parâmetros de pageable. Com isso, nas requisições que utilizam paginação,
  # devemos utilizar esses nomes que foram definidos.
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}

server:
  error:
    include-message: always
